[tool.poetry]
name = "searvey"
version = "0.1.0"
description = ""
authors = ["Panos Mavrogiorgos <pmav99@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.8"
requests = "^2.26"
pandas = "^1.3"
erddapy = "^1.1"
pytest-recording = "^0.12.0"

[tool.poetry.group.dev.dependencies]
black = "*"
ipython = "*"
pytest = "^6.2"
prospector = "^1.5"
pre-commit = "^2.15"
pytest-cov = "^2.12"

[tool.poetry.group.typing.dependencies]
mypy = "0.910"
types-requests = "^2.25"

[tool.poetry.group.doc.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 108
target-version = ['py39']

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --verbose --showlocals --tb=short --cov=searvey --cov-report term-missing"
testpaths = [
    "tests",
]
